site_name: quanbm
site_url: https://minhquan2904.github.io
repo_url: https://github.com/minhquan2904/minhquan2904.github.io
theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.jpg
  features:
    - search.suggest
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - announce.dismiss
plugins:
 - search
 - blog:
      blog_dir: . 
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
  version:
    provider: quanbm