site_name: quanbm
site_url: http://localhost:8000/
repo_url: https://github.com/minhquan2904/minhquan2904.github.io

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.jpg
  favicon: assets/favicon.jpg
  features:
    - search.suggest
    - navigation.tabs
    - navigation.insants
    - navigation.footer
    - announce.dismiss

plugins:
 - search
 - blog:
      blog_dir: . 
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
  version:
    provider: quanbm