site_name: quanbm
site_url: http://localhost:8000/
repo_url: https://github.com/minhquan2904/minhquan2904.github.io
nav:
  - Home: index.md
  - Hello-word: posts/hello-world.md
  - Docker: 
    - 'Tổng quan': posts/Docker/summary.md
    - 'Bài 1: Giới thiệu về Docker': posts/Docker/docker-start.md
  - Kafka:
    - 'So sánh Kafka và RabbitMQ': posts/Kafka/compare.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.jpg
  favicon: assets/favicon.jpg
  features:
    - search.suggest
    - navigation.indexes
    - navigation.insants
    - navigation.footer
    - announce.dismiss

plugins:
 - search

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
  version:
    provider: quanbm