site_name: quanbm
site_url: http://localhost:8000/
repo_url: https://github.com/minhquan2904/minhquan2904.github.io
nav:
  - Home: index.md
  - Hello-word: posts/hello-world.md
  - Docker: 
    - 'Tổng quan': posts/Docker/summary.md
    - 'Bài 1: Giới thiệu về Docker': posts/Docker/docker-start.md
  - Kafka:
    - 'So sánh Kafka và RabbitMQ': posts/Kafka/compare.md
  - Thuật toán:
    - 'Quicksort': posts/alth/quicksort.md
  - ABAC:
    - Các mô hình và phương pháp kiểm soát truy cập:
      - 'Thuật ngữ': posts/abac/AC/Terminology.md
      - 'Access Control Models and Policies': posts/abac/AC/ModelsAndPolicies.md
      - 'Policy Enforcement': posts/abac/AC/PolicyEnforcement.md
      - 'Discretionary Access Control - DAC': posts/abac/AC/dac.md
      - 'Mandatory Access Control - MAC': posts/abac/AC/mac.md
    - Mô hình và phương pháp tiếp cận ABAC:
      - 'Giới thiệu': posts/abac/ABAC/intro.md
      - 'Kiến trúc và thành phần chức năng của ABAC': posts/abac/ABAC/ArchitecturesandFunctionalComponents.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.jpg
  favicon: assets/favicon.jpg
  features:
    - search.suggest
    - navigation.indexes
    - navigation.insants
    - navigation.footer
    - announce.dismiss

plugins:
 - search

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
  version:
    provider: quanbm